from app.dev import bp
from flask import render_template, request

people = [
    {
        "first_name": "Herminio",
        "last_name": "Ryan",
        "role": "Central Applications Producer",
        "area": "Operations",
        "photo": "https://loremflickr.com/640/480?lock=7731726843379712",
    },
    {
        "first_name": "Cassandra",
        "last_name": "Schowalter",
        "role": "Investor Program Specialist",
        "area": "Marketing",
        "photo": "https://loremflickr.com/640/480?lock=2618619645132800",
    },
    {
        "first_name": "Justen",
        "last_name": "Stehr",
        "role": "Regional Usability Agent",
        "area": "Research",
        "photo": "https://picsum.photos/seed/hUTHQI5/640/480",
    },
    {
        "first_name": "Aliyah",
        "last_name": "Bogan",
        "role": "Lead Accounts Representative",
        "area": "Assurance",
        "photo": "https://picsum.photos/seed/80HbR/640/480",
    },
    {
        "first_name": "Pearl",
        "last_name": "Pacocha",
        "role": "Investor Interactions Producer",
        "area": "Directives",
        "photo": "https://picsum.photos/seed/7nJaoIW4w8/640/480",
    },
    {
        "first_name": "Treva",
        "last_name": "Hyatt",
        "role": "Chief Division Executive",
        "area": "Integration",
        "photo": "https://picsum.photos/seed/pJwdHZ5y/640/480",
    },
    {
        "first_name": "Kaci",
        "last_name": "Hudson",
        "role": "Forward Functionality Representative",
        "area": "Brand",
        "photo": "https://loremflickr.com/640/480?lock=3955353314131968",
    },
    {
        "first_name": "Keegan",
        "last_name": "Anderson",
        "role": "Customer Implementation Designer",
        "area": "Accounts",
        "photo": "https://picsum.photos/seed/9CjlesgB/640/480",
    },
    {
        "first_name": "Tyler",
        "last_name": "Harvey",
        "role": "Regional Creative Producer",
        "area": "Interactions",
        "photo": "https://picsum.photos/seed/mn4MWmEU/640/480",
    },
    {
        "first_name": "Leonie",
        "last_name": "Kohler",
        "role": "Investor Infrastructure Facilitator",
        "area": "Factors",
        "photo": "https://loremflickr.com/640/480?lock=5448772907696128",
    },
    {
        "first_name": "Sheldon",
        "last_name": "King",
        "role": "Central Markets Assistant",
        "area": "Branding",
        "photo": "https://picsum.photos/seed/LMFYE9Z3zT/640/480",
    },
    {
        "first_name": "Grayson",
        "last_name": "West",
        "role": "Customer Marketing Strategist",
        "area": "Implementation",
        "photo": "https://picsum.photos/seed/pj0OWpuo/640/480",
    },
    {
        "first_name": "Hermann",
        "last_name": "Wisoky",
        "role": "District Markets Technician",
        "area": "Research",
        "photo": "https://loremflickr.com/640/480?lock=4204517082005504",
    },
    {
        "first_name": "Esperanza",
        "last_name": "Beahan",
        "role": "Future Factors Director",
        "area": "Configuration",
        "photo": "https://loremflickr.com/640/480?lock=5581875275890688",
    },
    {
        "first_name": "Janessa",
        "last_name": "Johnston",
        "role": "District Response Agent",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=8549286889390080",
    },
    {
        "first_name": "Rosa",
        "last_name": "Daugherty",
        "role": "Corporate Program Analyst",
        "area": "Interactions",
        "photo": "https://picsum.photos/seed/ZwNJRCzw/640/480",
    },
    {
        "first_name": "Margret",
        "last_name": "Gulgowski",
        "role": "Central Creative Developer",
        "area": "Mobility",
        "photo": "https://loremflickr.com/640/480?lock=3105460609613824",
    },
    {
        "first_name": "Kaylin",
        "last_name": "Kling",
        "role": "Human Interactions Specialist",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/9oqKNzGMtB/640/480",
    },
    {
        "first_name": "Moshe",
        "last_name": "Cole",
        "role": "National Marketing Supervisor",
        "area": "Web",
        "photo": "https://picsum.photos/seed/wKCQw/640/480",
    },
    {
        "first_name": "Drew",
        "last_name": "Johnston",
        "role": "Direct Mobility Assistant",
        "area": "Accountability",
        "photo": "https://loremflickr.com/640/480?lock=8274024899543040",
    },
    {
        "first_name": "Karina",
        "last_name": "Christiansen",
        "role": "Central Intranet Director",
        "area": "Assurance",
        "photo": "https://loremflickr.com/640/480?lock=5669912510988288",
    },
    {
        "first_name": "Floyd",
        "last_name": "Padberg",
        "role": "District Quality Facilitator",
        "area": "Usability",
        "photo": "https://picsum.photos/seed/4DYjd/640/480",
    },
    {
        "first_name": "Lesley",
        "last_name": "Daniel",
        "role": "Legacy Division Producer",
        "area": "Operations",
        "photo": "https://picsum.photos/seed/Xcd6oh/640/480",
    },
    {
        "first_name": "Betty",
        "last_name": "Cronin",
        "role": "Future Usability Assistant",
        "area": "Research",
        "photo": "https://picsum.photos/seed/fhpLmU/640/480",
    },
    {
        "first_name": "Krista",
        "last_name": "Ernser",
        "role": "Product Mobility Planner",
        "area": "Communications",
        "photo": "https://loremflickr.com/640/480?lock=7332525615611904",
    },
    {
        "first_name": "Benedict",
        "last_name": "Thiel",
        "role": "Regional Marketing Executive",
        "area": "Intranet",
        "photo": "https://loremflickr.com/640/480?lock=3935183220768768",
    },
    {
        "first_name": "Berenice",
        "last_name": "Konopelski-Sanford",
        "role": "Product Solutions Agent",
        "area": "Marketing",
        "photo": "https://loremflickr.com/640/480?lock=2739375689433088",
    },
    {
        "first_name": "Rosemary",
        "last_name": "Hansen",
        "role": "Customer Applications Agent",
        "area": "Branding",
        "photo": "https://loremflickr.com/640/480?lock=7743580938436608",
    },
    {
        "first_name": "Kellen",
        "last_name": "Hegmann",
        "role": "Chief Applications Architect",
        "area": "Identity",
        "photo": "https://loremflickr.com/640/480?lock=7049731316383744",
    },
    {
        "first_name": "Gerald",
        "last_name": "Feil",
        "role": "District Functionality Facilitator",
        "area": "Solutions",
        "photo": "https://picsum.photos/seed/qUbQI5L/640/480",
    },
    {
        "first_name": "Andreanne",
        "last_name": "Christiansen",
        "role": "Internal Brand Producer",
        "area": "Program",
        "photo": "https://picsum.photos/seed/2KoxHx/640/480",
    },
    {
        "first_name": "Golda",
        "last_name": "Kemmer",
        "role": "Future Tactics Producer",
        "area": "Directives",
        "photo": "https://picsum.photos/seed/9gFdAS/640/480",
    },
    {
        "first_name": "Guiseppe",
        "last_name": "Haag",
        "role": "National Applications Specialist",
        "area": "Quality",
        "photo": "https://picsum.photos/seed/N4nJR6LPGN/640/480",
    },
    {
        "first_name": "Carlos",
        "last_name": "Kirlin",
        "role": "Corporate Intranet Facilitator",
        "area": "Data",
        "photo": "https://loremflickr.com/640/480?lock=6768959934169088",
    },
    {
        "first_name": "Krystal",
        "last_name": "Tremblay",
        "role": "Product Program Representative",
        "area": "Tactics",
        "photo": "https://loremflickr.com/640/480?lock=5405941237284864",
    },
    {
        "first_name": "Garrett",
        "last_name": "Rowe",
        "role": "Central Optimization Designer",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=2839401786769408",
    },
    {
        "first_name": "Anita",
        "last_name": "Bogisich",
        "role": "Human Functionality Orchestrator",
        "area": "Tactics",
        "photo": "https://loremflickr.com/640/480?lock=3105457889607680",
    },
    {
        "first_name": "Dylan",
        "last_name": "Klocko",
        "role": "Human Communications Supervisor",
        "area": "Marketing",
        "photo": "https://picsum.photos/seed/QtnUA/640/480",
    },
    {
        "first_name": "Okey",
        "last_name": "Yost",
        "role": "Investor Branding Consultant",
        "area": "Web",
        "photo": "https://loremflickr.com/640/480?lock=6787129004785664",
    },
    {
        "first_name": "Carson",
        "last_name": "Blanda",
        "role": "Internal Creative Coordinator",
        "area": "Response",
        "photo": "https://loremflickr.com/640/480?lock=7243949915766784",
    },
    {
        "first_name": "Zaria",
        "last_name": "Bednar",
        "role": "Internal Research Specialist",
        "area": "Functionality",
        "photo": "https://picsum.photos/seed/98gwy/640/480",
    },
    {
        "first_name": "Barton",
        "last_name": "Deckow",
        "role": "Global Creative Developer",
        "area": "Factors",
        "photo": "https://picsum.photos/seed/ItpSbeV/640/480",
    },
    {
        "first_name": "Kaia",
        "last_name": "Schowalter",
        "role": "Future Interactions Strategist",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/uCYzC/640/480",
    },
    {
        "first_name": "Ena",
        "last_name": "Borer",
        "role": "Senior Functionality Coordinator",
        "area": "Metrics",
        "photo": "https://picsum.photos/seed/9BCpc/640/480",
    },
    {
        "first_name": "Dakota",
        "last_name": "Wilkinson",
        "role": "Product Tactics Analyst",
        "area": "Implementation",
        "photo": "https://loremflickr.com/640/480?lock=8772775908999168",
    },
    {
        "first_name": "Vincent",
        "last_name": "Roberts",
        "role": "Direct Branding Associate",
        "area": "Directives",
        "photo": "https://loremflickr.com/640/480?lock=1391898528841728",
    },
    {
        "first_name": "Dock",
        "last_name": "Goodwin-Bernier",
        "role": "National Optimization Developer",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=384213310242816",
    },
    {
        "first_name": "Anabel",
        "last_name": "Sipes",
        "role": "Legacy Brand Designer",
        "area": "Implementation",
        "photo": "https://picsum.photos/seed/tLVfVLJdf/640/480",
    },
    {
        "first_name": "Ilene",
        "last_name": "Kulas",
        "role": "Product Group Administrator",
        "area": "Applications",
        "photo": "https://picsum.photos/seed/NCInGER4Vc/640/480",
    },
    {
        "first_name": "Allison",
        "last_name": "Paucek",
        "role": "Corporate Accountability Associate",
        "area": "Intranet",
        "photo": "https://loremflickr.com/640/480?lock=7540101032706048",
    },
    {
        "first_name": "Regan",
        "last_name": "Kuhic",
        "role": "Internal Markets Liaison",
        "area": "Mobility",
        "photo": "https://loremflickr.com/640/480?lock=8314383526526976",
    },
    {
        "first_name": "Kara",
        "last_name": "Boehm",
        "role": "Senior Factors Assistant",
        "area": "Quality",
        "photo": "https://picsum.photos/seed/8YASp/640/480",
    },
    {
        "first_name": "Marilie",
        "last_name": "Watsica",
        "role": "Corporate Branding Engineer",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/8Dg1mFcYQ2/640/480",
    },
    {
        "first_name": "Karen",
        "last_name": "Lemke",
        "role": "Direct Infrastructure Director",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=6251165566107648",
    },
    {
        "first_name": "Aurelia",
        "last_name": "Pollich",
        "role": "Legacy Functionality Orchestrator",
        "area": "Configuration",
        "photo": "https://picsum.photos/seed/3V68KUI/640/480",
    },
    {
        "first_name": "Jerrold",
        "last_name": "Vandervort",
        "role": "Corporate Security Executive",
        "area": "Factors",
        "photo": "https://loremflickr.com/640/480?lock=295506511134720",
    },
    {
        "first_name": "Jacquelyn",
        "last_name": "Hartmann",
        "role": "Forward Creative Strategist",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=1780348019015680",
    },
    {
        "first_name": "Elfrieda",
        "last_name": "DuBuque",
        "role": "Corporate Data Technician",
        "area": "Infrastructure",
        "photo": "https://loremflickr.com/640/480?lock=6929852917612544",
    },
    {
        "first_name": "Price",
        "last_name": "Kuphal",
        "role": "Principal Division Specialist",
        "area": "Functionality",
        "photo": "https://picsum.photos/seed/D4MHmV9k/640/480",
    },
    {
        "first_name": "Seth",
        "last_name": "Kub",
        "role": "Global Usability Planner",
        "area": "Accounts",
        "photo": "https://picsum.photos/seed/izlFO3/640/480",
    },
    {
        "first_name": "Francesca",
        "last_name": "Weissnat",
        "role": "Regional Data Analyst",
        "area": "Mobility",
        "photo": "https://loremflickr.com/640/480?lock=2164675458367488",
    },
    {
        "first_name": "Kathleen",
        "last_name": "Kreiger",
        "role": "Global Implementation Architect",
        "area": "Operations",
        "photo": "https://loremflickr.com/640/480?lock=7997132344655872",
    },
    {
        "first_name": "Emmett",
        "last_name": "Botsford",
        "role": "National Mobility Technician",
        "area": "Data",
        "photo": "https://loremflickr.com/640/480?lock=1453885463986176",
    },
    {
        "first_name": "Neva",
        "last_name": "Ondricka",
        "role": "Lead Implementation Administrator",
        "area": "Program",
        "photo": "https://picsum.photos/seed/jdeuMwRh/640/480",
    },
    {
        "first_name": "Missouri",
        "last_name": "Huels",
        "role": "National Response Developer",
        "area": "Security",
        "photo": "https://picsum.photos/seed/gGJIRmCx/640/480",
    },
    {
        "first_name": "Maymie",
        "last_name": "Hayes",
        "role": "Forward Optimization Assistant",
        "area": "Factors",
        "photo": "https://picsum.photos/seed/EkD5v/640/480",
    },
    {
        "first_name": "Eleanora",
        "last_name": "Torphy",
        "role": "Human Communications Strategist",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=7871479773396992",
    },
    {
        "first_name": "Sister",
        "last_name": "Dickens",
        "role": "District Marketing Architect",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=5155509252390912",
    },
    {
        "first_name": "Angel",
        "last_name": "DuBuque",
        "role": "Global Accountability Architect",
        "area": "Division",
        "photo": "https://picsum.photos/seed/I404QzVU/640/480",
    },
    {
        "first_name": "Felicity",
        "last_name": "Boehm",
        "role": "Principal Quality Producer",
        "area": "Interactions",
        "photo": "https://loremflickr.com/640/480?lock=2383316990820352",
    },
    {
        "first_name": "Tony",
        "last_name": "Kulas",
        "role": "Lead Configuration Specialist",
        "area": "Functionality",
        "photo": "https://picsum.photos/seed/ZMJaOv/640/480",
    },
    {
        "first_name": "Kayley",
        "last_name": "Blanda",
        "role": "Forward Accounts Supervisor",
        "area": "Directives",
        "photo": "https://loremflickr.com/640/480?lock=7039237652217856",
    },
    {
        "first_name": "Ena",
        "last_name": "Will",
        "role": "Dynamic Operations Developer",
        "area": "Group",
        "photo": "https://picsum.photos/seed/bLfgo4g6H/640/480",
    },
    {
        "first_name": "Jennie",
        "last_name": "D'Amore",
        "role": "Dynamic Identity Officer",
        "area": "Quality",
        "photo": "https://picsum.photos/seed/iKU4jCS/640/480",
    },
    {
        "first_name": "Mac",
        "last_name": "Berge",
        "role": "Central Response Architect",
        "area": "Research",
        "photo": "https://loremflickr.com/640/480?lock=273313764999168",
    },
    {
        "first_name": "Malcolm",
        "last_name": "Aufderhar",
        "role": "Future Group Facilitator",
        "area": "Division",
        "photo": "https://picsum.photos/seed/G2GWMq/640/480",
    },
    {
        "first_name": "Linwood",
        "last_name": "Kohler",
        "role": "Human Communications Assistant",
        "area": "Paradigm",
        "photo": "https://picsum.photos/seed/FH6epEF/640/480",
    },
    {
        "first_name": "Sim",
        "last_name": "Boehm",
        "role": "Central Assurance Coordinator",
        "area": "Usability",
        "photo": "https://picsum.photos/seed/E9zc8s/640/480",
    },
    {
        "first_name": "Lottie",
        "last_name": "MacGyver",
        "role": "Human Directives Supervisor",
        "area": "Branding",
        "photo": "https://loremflickr.com/640/480?lock=8514769998839808",
    },
    {
        "first_name": "Tad",
        "last_name": "Dare",
        "role": "Human Infrastructure Agent",
        "area": "Functionality",
        "photo": "https://loremflickr.com/640/480?lock=3613954016280576",
    },
    {
        "first_name": "Gust",
        "last_name": "Bahringer",
        "role": "Principal Solutions Facilitator",
        "area": "Data",
        "photo": "https://picsum.photos/seed/LxIeyA65X1/640/480",
    },
    {
        "first_name": "Alexandro",
        "last_name": "Raynor",
        "role": "Dynamic Accountability Orchestrator",
        "area": "Functionality",
        "photo": "https://loremflickr.com/640/480?lock=6826452651606016",
    },
    {
        "first_name": "Timmothy",
        "last_name": "Klocko",
        "role": "Human Applications Coordinator",
        "area": "Division",
        "photo": "https://picsum.photos/seed/EKZPxFG3jf/640/480",
    },
    {
        "first_name": "Magali",
        "last_name": "Metz",
        "role": "Direct Markets Agent",
        "area": "Data",
        "photo": "https://loremflickr.com/640/480?lock=5601787019001856",
    },
    {
        "first_name": "Reuben",
        "last_name": "Watsica",
        "role": "Customer Usability Engineer",
        "area": "Data",
        "photo": "https://picsum.photos/seed/SQNd75l/640/480",
    },
    {
        "first_name": "Melyna",
        "last_name": "Considine-Wolf",
        "role": "Investor Operations Facilitator",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=8872118957637632",
    },
    {
        "first_name": "Garfield",
        "last_name": "Gibson",
        "role": "Legacy Quality Technician",
        "area": "Infrastructure",
        "photo": "https://picsum.photos/seed/uCAKbNxZhX/640/480",
    },
    {
        "first_name": "Nichole",
        "last_name": "Romaguera",
        "role": "Direct Implementation Supervisor",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=7165529288605696",
    },
    {
        "first_name": "Athena",
        "last_name": "Larson",
        "role": "Future Brand Developer",
        "area": "Research",
        "photo": "https://picsum.photos/seed/ral11St7/640/480",
    },
    {
        "first_name": "Orion",
        "last_name": "Stoltenberg",
        "role": "International Solutions Producer",
        "area": "Interactions",
        "photo": "https://loremflickr.com/640/480?lock=8410566448119808",
    },
    {
        "first_name": "Noe",
        "last_name": "Collier",
        "role": "Regional Research Supervisor",
        "area": "Markets",
        "photo": "https://loremflickr.com/640/480?lock=8638150352044032",
    },
    {
        "first_name": "Coy",
        "last_name": "Kilback",
        "role": "Lead Markets Technician",
        "area": "Identity",
        "photo": "https://loremflickr.com/640/480?lock=5015730934251520",
    },
    {
        "first_name": "Bernie",
        "last_name": "Bogisich",
        "role": "Central Integration Designer",
        "area": "Interactions",
        "photo": "https://loremflickr.com/640/480?lock=4643254249193472",
    },
    {
        "first_name": "Heber",
        "last_name": "Schaefer",
        "role": "Direct Quality Architect",
        "area": "Marketing",
        "photo": "https://loremflickr.com/640/480?lock=7587165707960320",
    },
    {
        "first_name": "Chet",
        "last_name": "Monahan",
        "role": "Legacy Paradigm Coordinator",
        "area": "Marketing",
        "photo": "https://picsum.photos/seed/zjyhv9/640/480",
    },
    {
        "first_name": "Jordy",
        "last_name": "Gusikowski",
        "role": "Chief Security Specialist",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=5285376394526720",
    },
    {
        "first_name": "Savannah",
        "last_name": "Pollich",
        "role": "Senior Group Designer",
        "area": "Brand",
        "photo": "https://loremflickr.com/640/480?lock=4364541248929792",
    },
    {
        "first_name": "Jettie",
        "last_name": "Goyette",
        "role": "Human Branding Manager",
        "area": "Communications",
        "photo": "https://picsum.photos/seed/iejE82PRz/640/480",
    },
    {
        "first_name": "Maxime",
        "last_name": "Deckow",
        "role": "Lead Group Strategist",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/xZIxfQw/640/480",
    },
    {
        "first_name": "Mallory",
        "last_name": "Mraz",
        "role": "Dynamic Interactions Assistant",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/ZFVlfak/640/480",
    },
    {
        "first_name": "Felix",
        "last_name": "Mayer",
        "role": "Human Factors Orchestrator",
        "area": "Accountability",
        "photo": "https://loremflickr.com/640/480?lock=8402828653494272",
    },
    {
        "first_name": "Wilhelmine",
        "last_name": "Kerluke",
        "role": "Central Paradigm Designer",
        "area": "Directives",
        "photo": "https://picsum.photos/seed/fKI3HKs/640/480",
    },
    {
        "first_name": "Kelli",
        "last_name": "King",
        "role": "District Markets Executive",
        "area": "Usability",
        "photo": "https://loremflickr.com/640/480?lock=2614289584095232",
    },
    {
        "first_name": "Shanon",
        "last_name": "Lind",
        "role": "Forward Functionality Planner",
        "area": "Tactics",
        "photo": "https://picsum.photos/seed/BomBu/640/480",
    },
    {
        "first_name": "Theron",
        "last_name": "Gutkowski",
        "role": "Dynamic Branding Assistant",
        "area": "Web",
        "photo": "https://picsum.photos/seed/HoTUuPYX/640/480",
    },
    {
        "first_name": "Evalyn",
        "last_name": "Langworth",
        "role": "Corporate Factors Technician",
        "area": "Operations",
        "photo": "https://picsum.photos/seed/YHic8ivI/640/480",
    },
    {
        "first_name": "Odell",
        "last_name": "Dooley",
        "role": "Chief Branding Producer",
        "area": "Implementation",
        "photo": "https://picsum.photos/seed/44PM3ApD/640/480",
    },
    {
        "first_name": "Tristian",
        "last_name": "Sauer",
        "role": "Regional Creative Engineer",
        "area": "Interactions",
        "photo": "https://loremflickr.com/640/480?lock=306633703948288",
    },
    {
        "first_name": "Luigi",
        "last_name": "Will",
        "role": "Global Research Director",
        "area": "Tactics",
        "photo": "https://loremflickr.com/640/480?lock=1631975207075840",
    },
    {
        "first_name": "Ezequiel",
        "last_name": "Treutel",
        "role": "Customer Assurance Administrator",
        "area": "Web",
        "photo": "https://loremflickr.com/640/480?lock=7295967762055168",
    },
    {
        "first_name": "Heaven",
        "last_name": "Carter",
        "role": "National Tactics Executive",
        "area": "Paradigm",
        "photo": "https://loremflickr.com/640/480?lock=885359460220928",
    },
    {
        "first_name": "Martin",
        "last_name": "Streich",
        "role": "Forward Communications Specialist",
        "area": "Tactics",
        "photo": "https://loremflickr.com/640/480?lock=8252175255863296",
    },
    {
        "first_name": "Anya",
        "last_name": "Konopelski",
        "role": "Forward Communications Executive",
        "area": "Metrics",
        "photo": "https://picsum.photos/seed/xTwkQL/640/480",
    },
    {
        "first_name": "Luciano",
        "last_name": "Breitenberg",
        "role": "Human Optimization Representative",
        "area": "Response",
        "photo": "https://picsum.photos/seed/5HRXhz/640/480",
    },
    {
        "first_name": "Ila",
        "last_name": "Schamberger",
        "role": "Lead Division Director",
        "area": "Paradigm",
        "photo": "https://loremflickr.com/640/480?lock=263623637204992",
    },
    {
        "first_name": "Alvina",
        "last_name": "Stamm",
        "role": "Central Security Facilitator",
        "area": "Implementation",
        "photo": "https://loremflickr.com/640/480?lock=4541950084513792",
    },
    {
        "first_name": "Felicity",
        "last_name": "DuBuque",
        "role": "Direct Factors Architect",
        "area": "Data",
        "photo": "https://loremflickr.com/640/480?lock=2763028640563200",
    },
    {
        "first_name": "Kaylee",
        "last_name": "Block",
        "role": "National Usability Engineer",
        "area": "Integration",
        "photo": "https://loremflickr.com/640/480?lock=1496078859894784",
    },
    {
        "first_name": "Mertie",
        "last_name": "Barton",
        "role": "National Identity Supervisor",
        "area": "Configuration",
        "photo": "https://loremflickr.com/640/480?lock=3895098909655040",
    },
    {
        "first_name": "Imelda",
        "last_name": "Senger",
        "role": "Regional Markets Coordinator",
        "area": "Communications",
        "photo": "https://loremflickr.com/640/480?lock=809562301005824",
    },
    {
        "first_name": "Avis",
        "last_name": "Vandervort",
        "role": "Forward Accounts Technician",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/69FcMzByQt/640/480",
    },
    {
        "first_name": "Melissa",
        "last_name": "Hartmann",
        "role": "District Program Executive",
        "area": "Communications",
        "photo": "https://picsum.photos/seed/vjACWo/640/480",
    },
    {
        "first_name": "Toy",
        "last_name": "Hayes",
        "role": "Chief Security Strategist",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/pSrTx/640/480",
    },
    {
        "first_name": "Kathryn",
        "last_name": "Bins",
        "role": "Internal Operations Administrator",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=4157197346930688",
    },
    {
        "first_name": "Franco",
        "last_name": "Pfannerstill",
        "role": "Future Functionality Administrator",
        "area": "Operations",
        "photo": "https://picsum.photos/seed/yexTRTIndI/640/480",
    },
    {
        "first_name": "Trevion",
        "last_name": "Wilderman",
        "role": "Corporate Implementation Planner",
        "area": "Usability",
        "photo": "https://picsum.photos/seed/mBw3lX8O/640/480",
    },
    {
        "first_name": "Jefferey",
        "last_name": "Brown",
        "role": "National Division Consultant",
        "area": "Solutions",
        "photo": "https://loremflickr.com/640/480?lock=6293504974127104",
    },
    {
        "first_name": "Kobe",
        "last_name": "McClure",
        "role": "Investor Response Officer",
        "area": "Program",
        "photo": "https://loremflickr.com/640/480?lock=1100054341353472",
    },
    {
        "first_name": "Hershel",
        "last_name": "O'Conner",
        "role": "Dynamic Factors Technician",
        "area": "Accountability",
        "photo": "https://loremflickr.com/640/480?lock=7216919948034048",
    },
    {
        "first_name": "Everett",
        "last_name": "Bergnaum",
        "role": "Investor Communications Producer",
        "area": "Implementation",
        "photo": "https://loremflickr.com/640/480?lock=8456914910314496",
    },
    {
        "first_name": "Elizabeth",
        "last_name": "DuBuque",
        "role": "Senior Accounts Administrator",
        "area": "Mobility",
        "photo": "https://picsum.photos/seed/IImHpec/640/480",
    },
    {
        "first_name": "Russel",
        "last_name": "Kuphal",
        "role": "Senior Brand Planner",
        "area": "Response",
        "photo": "https://loremflickr.com/640/480?lock=4278414156496896",
    },
    {
        "first_name": "Terrell",
        "last_name": "Herzog",
        "role": "Regional Paradigm Representative",
        "area": "Creative",
        "photo": "https://loremflickr.com/640/480?lock=1837129919365120",
    },
    {
        "first_name": "Glenda",
        "last_name": "Fritsch",
        "role": "Central Tactics Orchestrator",
        "area": "Group",
        "photo": "https://loremflickr.com/640/480?lock=4006692811440128",
    },
    {
        "first_name": "Maxine",
        "last_name": "Larkin",
        "role": "Regional Metrics Executive",
        "area": "Tactics",
        "photo": "https://loremflickr.com/640/480?lock=8853820442411008",
    },
    {
        "first_name": "Howell",
        "last_name": "Wisozk",
        "role": "District Quality Administrator",
        "area": "Accountability",
        "photo": "https://picsum.photos/seed/bXCLxaf/640/480",
    },
    {
        "first_name": "Grayce",
        "last_name": "Heaney",
        "role": "District Group Associate",
        "area": "Interactions",
        "photo": "https://picsum.photos/seed/KEBV2CSn/640/480",
    },
    {
        "first_name": "Tito",
        "last_name": "O'Connell",
        "role": "Customer Applications Consultant",
        "area": "Infrastructure",
        "photo": "https://picsum.photos/seed/npZtpj4VFz/640/480",
    },
    {
        "first_name": "Bettie",
        "last_name": "Bergstrom",
        "role": "International Creative Agent",
        "area": "Quality",
        "photo": "https://picsum.photos/seed/qega3aoOnV/640/480",
    },
    {
        "first_name": "Jamar",
        "last_name": "Terry-Okuneva",
        "role": "Central Usability Assistant",
        "area": "Security",
        "photo": "https://loremflickr.com/640/480?lock=7285757913858048",
    },
    {
        "first_name": "Rosetta",
        "last_name": "Greenholt",
        "role": "Regional Optimization Supervisor",
        "area": "Interactions",
        "photo": "https://loremflickr.com/640/480?lock=7661993739681792",
    },
    {
        "first_name": "Josh",
        "last_name": "Stracke",
        "role": "Forward Infrastructure Developer",
        "area": "Interactions",
        "photo": "https://picsum.photos/seed/jKeZjixsfU/640/480",
    },
    {
        "first_name": "Hardy",
        "last_name": "Ernser",
        "role": "Direct Markets Technician",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=1105471939280896",
    },
    {
        "first_name": "Lucienne",
        "last_name": "Welch",
        "role": "Senior Applications Orchestrator",
        "area": "Solutions",
        "photo": "https://loremflickr.com/640/480?lock=2757613053804544",
    },
    {
        "first_name": "Amber",
        "last_name": "Connelly",
        "role": "Central Paradigm Architect",
        "area": "Response",
        "photo": "https://loremflickr.com/640/480?lock=1705243645575168",
    },
    {
        "first_name": "Orin",
        "last_name": "Spencer",
        "role": "Global Accountability Agent",
        "area": "Paradigm",
        "photo": "https://picsum.photos/seed/AvDcWbL/640/480",
    },
    {
        "first_name": "Clemmie",
        "last_name": "Herman",
        "role": "District Solutions Planner",
        "area": "Assurance",
        "photo": "https://picsum.photos/seed/pTJ86XxQz/640/480",
    },
    {
        "first_name": "Jazmyn",
        "last_name": "King",
        "role": "Investor Paradigm Consultant",
        "area": "Brand",
        "photo": "https://picsum.photos/seed/llWr1G6QF7/640/480",
    },
    {
        "first_name": "Donato",
        "last_name": "Johns",
        "role": "Senior Mobility Facilitator",
        "area": "Factors",
        "photo": "https://picsum.photos/seed/edqZb8JYjn/640/480",
    },
    {
        "first_name": "Fiona",
        "last_name": "Dickinson",
        "role": "Future Brand Engineer",
        "area": "Applications",
        "photo": "https://picsum.photos/seed/uQOBgPtX/640/480",
    },
    {
        "first_name": "Jedediah",
        "last_name": "Jacobi",
        "role": "Human Quality Facilitator",
        "area": "Security",
        "photo": "https://picsum.photos/seed/bFc2Smd/640/480",
    },
    {
        "first_name": "Clint",
        "last_name": "Botsford",
        "role": "Corporate Applications Developer",
        "area": "Directives",
        "photo": "https://loremflickr.com/640/480?lock=5765727715852288",
    },
    {
        "first_name": "Terrill",
        "last_name": "Douglas",
        "role": "Lead Tactics Orchestrator",
        "area": "Usability",
        "photo": "https://loremflickr.com/640/480?lock=2066306834628608",
    },
    {
        "first_name": "Darion",
        "last_name": "Sipes",
        "role": "Legacy Accountability Director",
        "area": "Factors",
        "photo": "https://picsum.photos/seed/jmx4Np4nvN/640/480",
    },
    {
        "first_name": "Adan",
        "last_name": "Schroeder",
        "role": "Regional Infrastructure Technician",
        "area": "Data",
        "photo": "https://loremflickr.com/640/480?lock=310957903446016",
    },
    {
        "first_name": "Howell",
        "last_name": "Considine",
        "role": "Regional Functionality Officer",
        "area": "Directives",
        "photo": "https://picsum.photos/seed/DgALD/640/480",
    },
    {
        "first_name": "Valentin",
        "last_name": "Ferry",
        "role": "Future Quality Developer",
        "area": "Branding",
        "photo": "https://picsum.photos/seed/HI8ME/640/480",
    },
    {
        "first_name": "Abe",
        "last_name": "Osinski",
        "role": "Regional Markets Strategist",
        "area": "Data",
        "photo": "https://picsum.photos/seed/60cxMR/640/480",
    },
    {
        "first_name": "Salvatore",
        "last_name": "Kris",
        "role": "Legacy Functionality Engineer",
        "area": "Group",
        "photo": "https://loremflickr.com/640/480?lock=7818870186311680",
    },
    {
        "first_name": "Edd",
        "last_name": "Hayes",
        "role": "Direct Research Officer",
        "area": "Operations",
        "photo": "https://loremflickr.com/640/480?lock=2293495664476160",
    },
    {
        "first_name": "Eva",
        "last_name": "Feil",
        "role": "Human Accountability Strategist",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/sj97yiuFj/640/480",
    },
    {
        "first_name": "Cecelia",
        "last_name": "Botsford",
        "role": "Human Identity Director",
        "area": "Research",
        "photo": "https://loremflickr.com/640/480?lock=7950316351782912",
    },
    {
        "first_name": "Coy",
        "last_name": "Kiehn",
        "role": "Forward Program Administrator",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/0D4Z3M43eF/640/480",
    },
    {
        "first_name": "Wilburn",
        "last_name": "Schultz",
        "role": "Principal Factors Director",
        "area": "Interactions",
        "photo": "https://picsum.photos/seed/JLhtKcDTV/640/480",
    },
    {
        "first_name": "Eve",
        "last_name": "Emmerich",
        "role": "Internal Paradigm Associate",
        "area": "Functionality",
        "photo": "https://picsum.photos/seed/9ysEcdBAbc/640/480",
    },
    {
        "first_name": "Celia",
        "last_name": "Daugherty",
        "role": "Senior Implementation Architect",
        "area": "Mobility",
        "photo": "https://picsum.photos/seed/EePhO6g/640/480",
    },
    {
        "first_name": "Keenan",
        "last_name": "Steuber",
        "role": "Dynamic Accounts Assistant",
        "area": "Tactics",
        "photo": "https://picsum.photos/seed/X2G6G/640/480",
    },
    {
        "first_name": "Kailee",
        "last_name": "McLaughlin",
        "role": "Forward Branding Analyst",
        "area": "Operations",
        "photo": "https://loremflickr.com/640/480?lock=7715325439115264",
    },
    {
        "first_name": "Lennie",
        "last_name": "Bechtelar",
        "role": "Regional Web Specialist",
        "area": "Directives",
        "photo": "https://picsum.photos/seed/3BpGEh/640/480",
    },
    {
        "first_name": "Ethelyn",
        "last_name": "Macejkovic",
        "role": "Global Program Supervisor",
        "area": "Web",
        "photo": "https://loremflickr.com/640/480?lock=1251658413637632",
    },
    {
        "first_name": "Mozelle",
        "last_name": "Donnelly",
        "role": "Forward Implementation Architect",
        "area": "Assurance",
        "photo": "https://picsum.photos/seed/Dyoy9/640/480",
    },
    {
        "first_name": "Lawrence",
        "last_name": "Gerlach",
        "role": "Customer Configuration Liaison",
        "area": "Integration",
        "photo": "https://loremflickr.com/640/480?lock=8412275887046656",
    },
    {
        "first_name": "Alessia",
        "last_name": "Breitenberg",
        "role": "International Optimization Supervisor",
        "area": "Security",
        "photo": "https://loremflickr.com/640/480?lock=4977308205056000",
    },
    {
        "first_name": "Monique",
        "last_name": "Mayert",
        "role": "Chief Directives Manager",
        "area": "Division",
        "photo": "https://picsum.photos/seed/KxjNtqM/640/480",
    },
    {
        "first_name": "Kellen",
        "last_name": "Wehner",
        "role": "Human Infrastructure Planner",
        "area": "Optimization",
        "photo": "https://loremflickr.com/640/480?lock=6121488373514240",
    },
    {
        "first_name": "Cordie",
        "last_name": "Goyette",
        "role": "International Usability Manager",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/xlyty/640/480",
    },
    {
        "first_name": "Elliot",
        "last_name": "Cummings",
        "role": "Central Tactics Supervisor",
        "area": "Markets",
        "photo": "https://picsum.photos/seed/YpMY2F/640/480",
    },
    {
        "first_name": "Nickolas",
        "last_name": "Collier",
        "role": "Senior Integration Architect",
        "area": "Mobility",
        "photo": "https://picsum.photos/seed/jF13i/640/480",
    },
    {
        "first_name": "Jerome",
        "last_name": "Abbott",
        "role": "Product Intranet Agent",
        "area": "Creative",
        "photo": "https://loremflickr.com/640/480?lock=8926718230265856",
    },
    {
        "first_name": "Winfield",
        "last_name": "Rowe",
        "role": "Dynamic Branding Engineer",
        "area": "Web",
        "photo": "https://loremflickr.com/640/480?lock=143932092579840",
    },
    {
        "first_name": "Alanis",
        "last_name": "Hickle",
        "role": "Forward Marketing Representative",
        "area": "Security",
        "photo": "https://picsum.photos/seed/CDBPkw/640/480",
    },
    {
        "first_name": "Brown",
        "last_name": "Carter",
        "role": "District Solutions Manager",
        "area": "Identity",
        "photo": "https://loremflickr.com/640/480?lock=2635115012292608",
    },
    {
        "first_name": "Alec",
        "last_name": "Mayert",
        "role": "Internal Division Executive",
        "area": "Implementation",
        "photo": "https://picsum.photos/seed/Y954LZ75Y/640/480",
    },
    {
        "first_name": "Patience",
        "last_name": "Parker",
        "role": "Central Quality Director",
        "area": "Paradigm",
        "photo": "https://picsum.photos/seed/46ews4/640/480",
    },
    {
        "first_name": "Brigitte",
        "last_name": "Ondricka-Lowe",
        "role": "Human Infrastructure Liaison",
        "area": "Marketing",
        "photo": "https://picsum.photos/seed/QoQ8LNA3G/640/480",
    },
    {
        "first_name": "Orval",
        "last_name": "Bergnaum",
        "role": "Regional Applications Manager",
        "area": "Creative",
        "photo": "https://picsum.photos/seed/jzePv/640/480",
    },
    {
        "first_name": "Westley",
        "last_name": "Marks",
        "role": "Lead Division Administrator",
        "area": "Usability",
        "photo": "https://loremflickr.com/640/480?lock=2790064929112064",
    },
    {
        "first_name": "Alexis",
        "last_name": "Kunde",
        "role": "International Accounts Facilitator",
        "area": "Integration",
        "photo": "https://picsum.photos/seed/YiXp5Yjk7/640/480",
    },
    {
        "first_name": "Julius",
        "last_name": "Mayert",
        "role": "District Division Facilitator",
        "area": "Tactics",
        "photo": "https://picsum.photos/seed/NR96x/640/480",
    },
    {
        "first_name": "Aryanna",
        "last_name": "Hane",
        "role": "Future Integration Representative",
        "area": "Optimization",
        "photo": "https://picsum.photos/seed/jEXuTqOKFl/640/480",
    },
    {
        "first_name": "Eugenia",
        "last_name": "Gottlieb",
        "role": "National Infrastructure Consultant",
        "area": "Accountability",
        "photo": "https://loremflickr.com/640/480?lock=7511187216400384",
    },
    {
        "first_name": "Delphine",
        "last_name": "Yundt",
        "role": "Senior Intranet Designer",
        "area": "Metrics",
        "photo": "https://loremflickr.com/640/480?lock=6183383696670720",
    },
    {
        "first_name": "Noe",
        "last_name": "Grady",
        "role": "Legacy Implementation Planner",
        "area": "Usability",
        "photo": "https://picsum.photos/seed/e8XKh/640/480",
    },
    {
        "first_name": "Kelly",
        "last_name": "Wehner",
        "role": "Legacy Assurance Administrator",
        "area": "Assurance",
        "photo": "https://loremflickr.com/640/480?lock=625688759500800",
    },
    {
        "first_name": "Nicole",
        "last_name": "Fadel",
        "role": "Direct Infrastructure Agent",
        "area": "Applications",
        "photo": "https://loremflickr.com/640/480?lock=6081832680423424",
    },
    {
        "first_name": "Arturo",
        "last_name": "Kris-Turcotte",
        "role": "Principal Functionality Producer",
        "area": "Operations",
        "photo": "https://loremflickr.com/640/480?lock=5893949275242496",
    },
    {
        "first_name": "Antonetta",
        "last_name": "Schinner",
        "role": "District Optimization Orchestrator",
        "area": "Brand",
        "photo": "https://loremflickr.com/640/480?lock=5992136151400448",
    },
    {
        "first_name": "Nella",
        "last_name": "Schoen",
        "role": "Forward Data Coordinator",
        "area": "Accounts",
        "photo": "https://loremflickr.com/640/480?lock=8829974643474432",
    },
    {
        "first_name": "Jamal",
        "last_name": "Grady",
        "role": "Principal Metrics Executive",
        "area": "Response",
        "photo": "https://loremflickr.com/640/480?lock=3806113946402816",
    },
    {
        "first_name": "Maybell",
        "last_name": "Anderson",
        "role": "Customer Applications Developer",
        "area": "Group",
        "photo": "https://picsum.photos/seed/G3iRRAI/640/480",
    },
]

roles = set()
for person in people:
    roles.add(person["role"].split()[-1])


@bp.route("/people/")
def people_list():
    people_sorted = sorted(
        people, key=lambda d: (d["last_name"], d["first_name"])
    )
    if request.args.get("role"):
        people_sorted = [
            person
            for person in people_sorted
            if person["role"].lower().split()[-1] == request.args.get("role")
        ]
    return render_template(
        "dev/people.html",
        people=people_sorted,
        people_length=len(people),
        roles=sorted(roles),
    )
