name: Run Python tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: snok/install-poetry@v1
      with:
        version: 1.8.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
    - name: Install Poetry dependencies
      run: poetry install --no-interaction --no-root
      shell: bash
    - name: Make tmp directory
      run: mkdir tmp
      shell: bash
    - name: Clone ds-wagtail
      run: cd tmp && git clone https://github.com/nationalarchives/ds-wagtail.git ds-wagtail
      shell: bash
    - name: Run Python tests
      run: poetry run python -m pytest
      shell: bash
