name: Run Node tests

runs:
  using: "composite"
  steps:
    - name: Install Node dependencies
      run: npm install
      shell: bash
    - name: Run Node tests
      run: npm run test:all
      shell: bash
    # TODO: Re-enable audit when vulnerabilities are fixed (https://github.com/videojs/video.js/issues/9103)
    # - name: Audit Node dependencies
    #   run: npm audit
    #   shell: bash
